swerve_controller:
  ros__parameters:

    robot_base_frame: chassis_ground_link

    twist_topic: cmd_vel

    position_controller_name: "drive_module_steering_angle_controller"
    velocity_controller_name: "drive_module_velocity_controller"

    cycle_frequency: 5

    steering_joints:
      - joint_actuator_servo_front_right
      - joint_actuator_servo_front_left
      - joint_actuator_servo_rear_right
      - joint_actuator_servo_rear_left

    drive_joints:
      - joint_actuator_wheel_front_right
      - joint_actuator_wheel_front_left
      - joint_actuator_wheel_rear_right
      - joint_actuator_wheel_rear_left
